language: go
go_import_path: github.com/vouch/vouch-proxy

sudo: false

services:
  - docker

go:
  - "1.13"

env:
  - ISTRAVIS=true

before_install:
  - ./do.sh goget
  # - go get github.com/golang/lint/golint # Linter
  # - go get github.com/fzipp/gocyclo

script:
  - GO_FILES=$(find . -iname '*.go' -type f)
  - test -z $(gofmt -s -l $GO_FILES) # Fail if a .go file hasn't been formatted with gofmt
  - ./do.sh build
  - ./do.sh test
#  - docker build -t $TRAVIS_REPO_SLUG .

#deploy:
#  - provider: script
#    skip_cleanup: true
#    script: bash .travis/docker_push
#    on:
#      go: "1.10"
#      branch: master
#  - provider: script
#    skip_cleanup: true
#    script: bash .travis/docker_push
#    on:
#      go: "1.10"
#      tags: true
#
notifications:
  irc: "chat.freenode.net#vouch"
