vouch:
  logLevel: info
  listen: 0.0.0.0
  port: 9090
  domains:
  - voucher.github.io

  whiteList:
  - bob@yourdomain.com
  - alice@yourdomain.com
  - joe@yourdomain.com


oauth:
  provider: indieauth
  client_id: http://voucher.github.io
  auth_url: https://indielogin.com/auth
  callback_url: http://voucher.github.io:9090/auth
